config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	root to: "day_habits#index"

	# Area.all.each do |area|
	# 	get "/#{area.path}", controller: "areas", action: area.dashboard_action
	# end

	get "/day_habits/:date", to: "day_habits#show",  as: :day_habit
	get "/day_habits",       to: "day_habits#index", as: :day_habits

	resources :brands
  resources :cities
	resources :drugs
	resources :drug_forms
	resources :drug_intakes do
		post :duplicate, on: :member
	end
	resources :excercises
	resources :habit_entries
	resources :habit_stats
	resources :habits do
		post :move, on: :member
	end
	resources :health_markers
	resources :labs
	resources :measurements
	resources :measurements_groups
	resources :moods
	resources :mood_entries
	resources :muscles
	resources :settings, only: [:index, :edit, :update]
	resources :substances
	resources :workouts do
		post :duplicate, on: :member
		post :yesterday, on: :member
	end


	# Devise

	devise_for :users,
							controllers: { registrations: "registrations" },
							path_names: { sign_in: "login", sign_out: "logout" }

end

app/controllers/day_habits_controller.rb
# frozen_string_literal: true

class DayHabitsController < DashboardsController

	# /day_habits/
	# /day_habits/?date=today
	# /day_habits/?date=yesterday
	# /day_habits/?date=2019-05-29
	def index
		today = Time.current.to_date
		@date = case params[:date]
						when nil         then today
						when "today"     then today
						when "yesterday" then today.advance(days: -1)
						else Date.parse params[:date]
						end
		@day_habits = Habit.order(:position).map do |habit|
										DayHabit.new(date: @date, habit: habit)
									end
	end

	# /day_habits/2019-05-29?habit_id=1
	def show
		@date      = Date.parse params[:date]
		@habit     = Habit.find params[:habit_id]
		@day_habit = DayHabit.new(date: @date, habit: @habit)
	end

	# /day_habits/increment_habit_entries?habit_id=1&date=2019-05-25
	# def increment_habit_entries
	#   filtered_params = params.permit(:date, :habit_id)
	# end

end

app/views/day_habits/_tr.html.slim
- habit = day_habit.habit

tr data-habit-id=habit.id class=("tr-completed-1" if day_habit.completed?)
	td = proofread habit.name
	td.day-habits__td-done
		- if day_habit.time_based?
			=> day_habit.done_time.in(habit.time_unit).to_i
			=> habit.time_unit
			| in 
		= t :rounds, count: day_habit.done_rounds

	td
		.progress
			.progress-bar class=("bg-success" if day_habit.completed?) style="width: #{day_habit.completed_percent}%"

	td.nobr = day_habit.target_str

	td
		- if day_habit.entries.any?
			= form_with model: day_habit.entries.last, method: :delete, html: { style: "display: inline-block;" } do |f|
				= f.hidden_field :date, value: day_habit.date
				= f.button "–", class: "increment-btn-2 increment-btn-2--danger", data: { behavior: "ajax-btn-1" }
		- else
			button class="increment-btn-2" disabled="disabled" –

		= form_with model: HabitEntry.new, html: { style: "display: inline-block; margin-left: 5px;" } do |f|
			= f.hidden_field :habit_id, value: habit.id
			= f.hidden_field :date, value: day_habit.date
			= f.button "+", class: "increment-btn-2 increment-btn-2--success", data: { behavior: "ajax-btn-1" }

app/views/day_habits/index.html.slim
.container-fluid.section-padding

	.page-header
		h1 style="margin-bottom: 0px" = l @date, format: "%-d %B"

		p.text-muted.small You have #{distance_of_time_in_words(Time.current.end_of_day - Time.current)}

		.day-habits__select-day style="margin-bottom: 40px; margin-top: 30px"
			- previous_day = @date.advance(days: -1)
			- next_day     = @date.advance(days: 1)

			= link_to "← #{l previous_day, format: "%-d %B"}", "/day_habits?date=#{previous_day}"
			= link_to "#{l next_day, format: "%-d %B"} →",     "/day_habits?date=#{next_day}", style: "margin-left: 20px" if @date < Date.today
			= link_to "Today",                                 "/day_habits?date=today",       style: "margin-left: 20px" unless @date.today?

	table.table
		thead
			tr
				th Name
				th.day-habits__th-done Done by now
				th Progress
				th Day target
				th Increment

		tbody = render collection: @day_habits, partial: "day_habits/tr", as: :day_habit

app/views/day_habits/show.html.slim
.container-fluid.section-padding

	h1 style="margin-bottom: 10px"
		=> @habit.name
		| on
		=< l @date, format: "%-d %B %Y"

	div style="margin-bottom: 40px"
		| ←
		=< link_to "All habits on #{l @date, format: "%-d %B %Y"}", day_habits_path(date: @date.strftime("%F"))

	h2 Entries

	table.table
		thead
			tr
				th Time
				th

		tbody
			- @day_habit.entries.each do |entry|
				tr
					td = entry.created_at
					td